language : java
jdk :
  - openjdk8

# 어느 브랜치가 푸쉬될 때 Travis CI를 수행할지 지정한다.
branches:
  only :
    - main

# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여,
# 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정합니다.
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-webservice *
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECERT_KEY
    bucket: freelec-springboot-build-jeong
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    # travis에서 master 브랜치가 default로 설정이 되어있다. main 브랜치도 가능하게 설정한다.
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-build-jeong
    key: springboot-webservice.zip
    bundle_type: zip
    application: freelec-springboot2-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: freelec-springboot2-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    # travis에서 master 브랜치가 default로 설정이 되어있다. main 브랜치도 가능하게 설정한다.
    on:
      all_branches: true
# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - jeonggu223@gmail.com